on: [push]


jobs:
  hello_world_job:
    runs-on: windows-latest
    name: A job to say hello
    steps:
    - name: Hello world action step
      id: hello
      uses: HassanOnsori/my-first-action@v9
    # Use the output from the `hello` step
    - name: Get the output time
      run: echo "The time was ${{ steps.hello.outputs.time }}"
    # - name: Broken Link Check
    #   uses: technote-space/broken-link-checker-action@v1
    - name: Run Gosec Security Scanner
      uses: securego/gosec@master


